version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    working_dir: /app
    command: npm run dev
    ports: ["5000:5000"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/plant_detect
      - AI_SERVICE_URL=http://ai-service:5001/predict
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
      - ai-service

  ai-service:
    build: ./ai-service
    command: python app.py
    ports: ["5001:5001"]
    volumes:
      - ./ai-service:/app

volumes:
  mongo-data:
